<?php

namespace AppBundle\Repository;

/**
 * interventionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class interventionRepository extends \Doctrine\ORM\EntityRepository
{
}
