<?php

namespace AppBundle\Repository;

/**
 * recolteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class recolteRepository extends \Doctrine\ORM\EntityRepository
{
}
