<?php

namespace AppBundle\Repository;

/**
 * rucheRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class rucheRepository extends \Doctrine\ORM\EntityRepository
{
}
